import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { signIn } from 'next-auth/react'
import LogInBtn from './components/LogInBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../pages/api/auth/[...nextauth]';
import LogOutBtn from './components/LogOutBtn';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let session = await getServerSession(authOptions)
  if (session){
    console.log(session)
  }
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {
            session ?  (<div>{session.user?.name}<LogOutBtn /></div>): <LogInBtn />
          }
        </div>
        {children}
      </body>
    </html>
  )
}
